Update Dist_ntj221.py
cranmer/intro-exp-phys-II pull request #196
Opened 2020-05-04 00:18 UTC by Nojoson

2020-05-04 12:41 UTC, cranmer requested changes
You need to delete this file or it will cause conflicts with others. 
Please delete file. Commit. and then push your changes to GitHub. 
That will update your pull request.

2020-05-04 21:51 UTC, cranmer commented
The automated test are now working. it indicates the mean is wrong
https://travis-ci.com/github/cranmer/intro-exp-phys-II/builds/163693307#L310

2020-05-05 14:43 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		self.f_max = 65/120
the maximum of your function x**4+7/8*x**2 occurs when x=1, right? If so, what is f_max ?

2020-05-05 14:43 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		return x**4+(7/8)*x**2
I didn't check this is properly normalized. Is it?

2020-05-05 14:43 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		return x**4+(7/8)*x**2
https://www.wolframalpha.com/input/?i=Integrate%5Bx**4%2B%287%2F8%29*x**2%2C%7Bx%2C0%2C1%7D%5D

2020-05-10 17:25 UTC, Nojoson commented on distributions/Dist_ntj221.py
> +		return x**4+(7/8)*x**2
I believe I have fixed the problem a few days ago. Has it been updated yet?

2020-05-18 23:05 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		return (120/59)*x**4+(7/8)*x**2
almost...
`(120/59)*(x**4+(7/8)*x**2)`

2020-05-18 23:06 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		return (120/59)*x**4+(7/8)*x**2
Ugh, I wrote this comment a long time ago, but I didn't submit it properly. Looks like you fixed it.

2020-05-18 23:07 UTC, cranmer commented on distributions/Dist_ntj221.py
> +		return (120/59)*x**4+(7/8)*x**2
Just need some ()

2020-05-19 00:13 UTC, Nojoson commented on distributions/Dist_ntj221.py
> +		return (120/59)*x**4+(7/8)*x**2
Ok the distribution should be all correct now.

2020-05-19 01:04 UTC, merged

2020-05-19 01:05 UTC, cranmer commented
I've merged this. You can work on part 2 now, but you will need to edit `distributions/__init__.py` to include your distribution.